import { type ActionFunctionArgs, data } from "react-router";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { parseMarkdownToJson, parseTripData } from "@/lib/utils";
import { supabase } from "~/lib/supabase";
import { createProduct } from "~/lib/stripe";
import type { Trip } from "~/index";

export const action = async ({ request }: ActionFunctionArgs) => {
    const {
        country,
        numberOfDays,
        travelStyle,
        interests,
        budget,
        groupType,
        userId,
    } = await request.json();

    const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);
    const unsplashApiKey = process.env.UNSPLASH_ACCESS_KEY!;

    try {
        const prompt = `Generate a ${numberOfDays}-day travel itinerary for ${country} based on the following user info:
        Budget: '${budget}'
        Interests: '${interests}'
        TravelStyle: '${travelStyle}'
        GroupType: '${groupType}'
        
        CRITICAL: Return ONLY a clean JSON object wrapped in \`\`\`json \`\`\` markdown blocks.
        The JSON must follow this exact structure:
        {
          "name": "Catchy Trip Title",
          "description": "Short summary (max 100 words)",
          "estimatedPrice": "$PriceRange",
          "duration": ${numberOfDays},
          "budget": "${budget}",
          "travelStyle": "${travelStyle}",
          "country": "${country}",
          "interests": "${interests}",
          "groupType": "${groupType}",
          "bestTimeToVisit": ["Season/Month range: Reason"],
          "weatherInfo": ["Season: Temp range"],
          "location": {
            "city": "Primary City",
            "coordinates": [lat, lon],
            "openStreetMap": "OSM link"
          },
          "itinerary": [
            {
              "day": 1,
              "location": "City Name",
              "activities": [
                {"time": "Morning", "description": "Short description with emoji"}
              ]
            }
          ]
        }`;

        const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });
        const textResult = await model.generateContent([prompt]);
        const responseText = textResult.response.text();

        const trip = parseMarkdownToJson(responseText) as any;
        if (!trip) throw new Error("Failed to parse Gemini response");

        // Fetch images
        let imageUrls: string[] = [];
        try {
            const imageResponse = await fetch(
                `https://api.unsplash.com/search/photos?query=${country} ${interests} ${travelStyle}&client_id=${unsplashApiKey}`
            );
            const imageData = await imageResponse.json();
            imageUrls = imageData.results?.slice(0, 3).map((result: any) => result.urls?.regular) || [];
        } catch (imgErr) {
            console.error("Image search error:", imgErr);
        }

        const { data: result, error: insertError } = await supabase
            .from('trips')
            .insert({
                trip_details: JSON.stringify(trip),
                created_at: new Date().toISOString(),
                image_urls: imageUrls,
                user_id: userId,
                name: trip.name || `${country} Trip`,
                estimated_price: trip.estimatedPrice || budget,
                tags: [travelStyle, groupType].filter(Boolean),
                duration: numberOfDays,
                description: trip.description || ""
            })
            .select()
            .single();

        if (insertError) throw insertError;

        let paymentLinkUrl = "";
        try {
            const tripPriceStr = (trip.estimatedPrice || "").replace(/[$,]/g, '').split('-')[0].trim();
            const tripPrice = parseInt(tripPriceStr, 10) || 1000;

            const paymentLink = await createProduct(
                trip.name || "Custom Trip",
                trip.description || "Generated by AI",
                imageUrls,
                tripPrice,
                result.id
            );
            paymentLinkUrl = paymentLink.url;
        } catch (err) {
            console.error("Stripe error:", err);
        }

        if (paymentLinkUrl) {
            await supabase
                .from('trips')
                .update({ payment_link: paymentLinkUrl })
                .eq('id', result.id);
        }

        return data({ id: result.id });
    } catch (e: any) {
        console.error('Error generating travel plan: ', e);
        return data({ error: e.message || "Failed to generate trip" }, { status: 500 });
    }
}
